apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-provider
  namespace: flux-system
spec:
  type: slack
  channel: "channel-name" # ganti dengan nama channel kamu
  secretRef:
    name: slack-url