name: Flask test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # run on Ubuntu OS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (apt)
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc libffi-dev python3-dev

    - name: Install pip dependencies
      working-directory: python-ci
      run: make install

    - name: Run tests
      working-directory: python-ci
      run: |
        . venv/bin/activate
        pytest

    - name: Install Docker (latest version)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    
    - name: Check Docker version
      run: docker --version

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build Docker image
      working-directory: python-ci
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-ci:v1.0.0 .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-ci:v1.0.0
