name: Flask test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # run on Ubuntu OS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (apt)
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc libffi-dev python3-dev

    - name: Install pip dependencies
      working-directory: python-ci
      run: make install

    - name: Run tests
      working-directory: python-ci
      run: |
        . venv/bin/activate
        pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0
      with:
        version: latest

    - name: Build Docker image
      working-directory: python-ci
      run: docker buildx build -f .Dockerfile ${{ secrets.DOCKER_USERNAME }}/python-ci:v1.0.0 . --push
